env:
  - name: RUST_LOG
    value: "sparker_forge=debug"
  - name: CHAIN_ID
    value: "FUEL"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: sparker-orderbook-database-app
        key: uri
  - name: MARKET_ID
    value: "0x81e83f73530c262b0dbf5414649a875c48a48144de3c08ff68cb9d54b36f2eaa"
