replicaCount: 1

image:
  repository: harbor.infra.sprk.fi/sprk/sparker-orderbook
  pullPolicy: IfNotPresent
  tag: main

nameOverride: ""
fullnameOverride: ""

env:
  - name: RUST_LOG
    value: "sparker_forge=debug"
  - name: CHAIN_ID
    value: "FUEL"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: sparker-orderbook-database-app
        key: uri
  - name: MARKET_ID
    value: "0xfe2c524ad8e088f33d232a45dbea43e792861640b71aa1814b30506bf8430ee5"

secrets:
  secretName: sparker-forge

vault:
  name: sparker-orderbook

database:
  name: sparker-orderbook-database
  instances: 1
  storage:
    size: 1Gi
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  enabled: false

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
