replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: sparker-api.v12.trade
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sparker-api-tls
      hosts:
        - sparker-api.v12.trade

vault:
  mount: production
