services:
  # forge:
  #   build: .
  #   env_file:
  #     - .env
  #   environment:
  #     RUST_LOG: sparker_forge=debug
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/orderbook
  #   depends_on:
  #     - postgres
  postgres:
    image: postgres
    user: postgres
    environment:
      POSTGRES_DB: orderbook
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
