[package]
name = "sparker-entity"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true, features = ["derive"] }
utoipa = { version = "5.1.3", features = ["chrono"] }
