replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: sparker-grpc.production.sprk.fi
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sparker-grpc-tls
      hosts:
        - sparker-grpc.production.sprk.fivault:

  mount: production
