replicaCount: 1

image:
  repository: harbor.infra.sprk.fi/sprk/sparker-orderbook
  pullPolicy: Always
  tag: main

nameOverride: ""
fullnameOverride: ""

command: ["/app/sparker-grpc"]

env:
  - name: RUST_LOG
    value: "sparker_grpc=debug"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: sparker-orderbook-database-app
        key: uri

secrets:
  secretName: sparker-grpc

vault:
  name: sparker-orderbook

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: true
  className: cilium
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"

livenessProbe:
  grpc:
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  grpc:
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
