ingress:
  enabled: true
  hosts:
    - host: sparker-grpc.staging.sprk.fi
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: sparker-grpc-tls
      hosts:
        - sparker-grpc.staging.sprk.fi

vault:
  mount: staging
