[package]
name = "sparker-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = { workspace = true }
tonic = { workspace = true }
tonic-types = { workspace = true }
strum = { version = "0.26", features = ["derive"] }

[build-dependencies]
tonic-build = "0.12.3"
