//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "limit_type")]
#[serde(rename_all = "snake_case")]
pub enum LimitType {
    #[sea_orm(string_value = "gtc")]
    Gtc,
    #[sea_orm(string_value = "ioc")]
    Ioc,
    #[sea_orm(string_value = "fok")]
    Fok,
    #[sea_orm(string_value = "mkt")]
    Mkt,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_status")]
#[serde(rename_all = "snake_case")]
pub enum OrderStatus {
    #[sea_orm(string_value = "new")]
    New,
    #[sea_orm(string_value = "partially_matched")]
    PartiallyMatched,
    #[sea_orm(string_value = "matched")]
    Matched,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
    #[sea_orm(string_value = "failed")]
    Failed,
}
#[derive(
    Debug,
    Clone,
    PartialEq,
    Eq,
    EnumIter,
    DeriveActiveEnum,
    Serialize,
    Deserialize,
    utoipa :: ToSchema,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "order_type")]
#[serde(rename_all = "snake_case")]
pub enum OrderType {
    #[sea_orm(string_value = "buy")]
    Buy,
    #[sea_orm(string_value = "sell")]
    Sell,
}
